name: Continuous integration bank

on:
  pull_request: 
    branches: [ dev ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install git
      run: sudo apt-get install git
    - name: Install gcc
      run: sudo apt-get install gcc
    - name: Compile main.c
      run: gcc main.c -o main
    - name: Config Git
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir test
        cd test
        git init
        git remote add web https://"AJulianah":$ACCES_TOKEN@github.com/AJulianah/web_api.git
        git pull web api_developpement
        ls
  automerge:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: reitermarkus/automerge@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            merge-method: rebase
            pull-request: ${{ github.event.inputs.pull-request }}
            dry-run: true
    
