name: Continuous integration bank

on:
  push:
    branches: [ dev ]
  pull_request: 
    branches: [ dev ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install git
      run: sudo apt-get install git
    - name: Install gcc
      run: sudo apt-get install gcc
    - name: Compiling and run the code
      run: |
        gcc main.c -o main
        ./main
    - name: Config Git
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir test
        cd test
        git init
        git remote add web https://"AJulianah":$ACCES_TOKEN@github.com/AJulianah/web_api.git
        git pull web api_developpement
        ls
